services:
  - type: worker
    name: shrutimusic
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: bash start
    envVars:
      - key: API_ID
        value: "24513216"
      - key: API_HASH
        value: "2079c79959648d8bbd992c4101bfcda2"
      - key: BOT_TOKEN
        value: "7533599560:AAEQt8PFmECEvlYr4ZpCyeG4Tcew1zfrreo"
      - key: MONGO_DB_URI
        value: "mongodb+srv://MAHAVIRKUMAR123:MAHAVIRKUMAR123@cluster0.oduviix.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: OWNER_ID
        value: "7557581984"
      - key: OWNER_USERNAME
        value: "Richedhacker"
      - key: STRING_SESSION
        value: "1BVtsOKEBuyBpblkAxddK8W5rTn2YPY2uUpYOsHsvGAw_-mkvWcByvBtEuPwJ9xmaU69F0AEeUH8BgaskZAbunOtCvNTlLBNzMakgIIyS6LE-Qy61f7f3hbMPxxFB2VW_vSi5MdRCQuMSzIHKmfwq1-2bhIHBZd9ek0yVy4tvqJJHmMQaYhkwKb4KmQDp6JpWnY77Dmeqe9KYuqBybHSPzROfyGUj4hXcT-3CcuTgNBBsQUGz_oIiI8qOg3j73ixQnl_AmDsi7cYSGUOFsKz0NdigFvlNlAu8RgbJ7iYX04Zp1A0_XmgY_rZLPZPQAwdCnDUy1PfSHHWJO6OI6W0zWbIIn2bEmm4="
      - key: GIT_TOKEN
        value: ""
      - key: HEROKU_API_KEY
        value: ""
      - key: HEROKU_APP_NAME
        value: ""
      - key: LOG_GROUP_ID
        value: "-1002657124059"
      - key: SUPPORT_GROUP
        value: "https://t.me/+VV9jWHN83js2MTdl"
      - key: SUPPORT_CHANNEL
        value: "https://t.me/richedmod"
      - key: COOKIE_URL
        value: "Need , IF You Didn't add Cookies file in cookies folder"
